languageCode = "en-us"
title = "MDN Fiori"
baseURL = "https://schalkneethling.github.io/mdn-fiori/"
canonifyURLs = true
theme = "cupper"
publishDir = "docs"

[params]
  description = "Documentation for the MDN Web Docs front-end code base"
  codePenUser = "schalk-neethling"
